export const featuredProperties = [
  {
    id: 1,
    title: "Luxury Villa in Mumbai",
    price: "₹2,50,00,000",
    beds: 4,
    baths: 3,
    sqft: "4,500",
    location: "Bandra, Mumbai",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=500&h=400&fit=crop",
    badge: "Featured",
    type: "Villa",
    featured: true,
  },
  {
    id: 2,
    title: "Modern Apartment in Bangalore",
    price: "₹1,25,00,000",
    beds: 3,
    baths: 2,
    sqft: "2,200",
    location: "Koramangala, Bangalore",
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=500&h=400&fit=crop",
    badge: "Hot Deal",
    type: "Apartment",
    featured: true,
  },
  {
    id: 3,
    title: "Spacious House in Delhi",
    price: "₹95,00,000",
    beds: 5,
    baths: 3,
    sqft: "3,800",
    location: "Dwarka, Delhi",
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=500&h=400&fit=crop",
    badge: "New",
    type: "House",
    featured: true,
  },
  {
    id: 4,
    title: "Premium Penthouse in Pune",
    price: "₹3,50,00,000",
    beds: 4,
    baths: 4,
    sqft: "5,200",
    location: "Koregaon Park, Pune",
    image: "#",
    badge: "Luxury",
    type: "Villa",
    featured: true,
  },
  {
    id: 5,
    title: "Contemporary Villa in Goa",
    price: "₹1,80,00,000",
    beds: 3,
    baths: 3,
    sqft: "3,200",
    location: "Calangute, Goa",
    image: "#",
    badge: "Featured",
    type: "Villa",
    featured: true,
  },
  {
    id: 6,
    title: "Smart Home in Hyderabad",
    price: "₹85,00,000",
    beds: 3,
    baths: 2,
    sqft: "2,100",
    location: "HITEC City, Hyderabad",
    image: "#",
    badge: "Smart",
    type: "Apartment",
    featured: true,
  },
];
