export const featuredProperties = [
  {
    id: 1,
    title: "Luxury Villa in Mumbai",
    price: "₹2,50,00,000",
    rawPrice: 25000000,
    beds: 4,
    baths: 3,
    sqft: "4,500",
    location: "Bandra, Mumbai",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop",
    badge: "Featured",
    type: "Villa",
    propertyType: "villa",
    purpose: "buy",
    featured: true,
    latitude: 19.0596,
    longitude: 72.8295,
    // New Details
    configuration: "4 BHK Ultra-Luxury",
    facing: "West Facing",
    isLand: false,
    parking: "2 Covered Car Parks",
    furnishing: "Fully Furnished",
    policies: "Pet Friendly, 24/7 Security",
  },
  {
    id: 2,
    title: "Modern Apartment in Bangalore",
    price: "₹1,25,00,000",
    rawPrice: 12500000, 
    beds: 3,
    baths: 2,
    sqft: "2,200",
    location: "Koramangala, Bangalore",
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop",
    badge: "Hot Deal",
    type: "Apartment",
    propertyType: "apartment",
    purpose: "buy",
    featured: true,
    latitude: 12.9352,
    longitude: 77.6245,
    // New Details
    configuration: "3 BHK Premium Flat",
    facing: "East Facing",
    isLand: false,
    parking: "1 Semi-Covered Car Park",
    furnishing: "Semi-Furnished",
    policies: "Standard Association Guidelines Apply",
  },
  {
    id: 3,
    title: "Spacious House in Delhi",
    price: "₹85,000 / month",
    rawPrice: 85000,
    beds: 5,
    baths: 3,
    sqft: "3,800",
    location: "Dwarka, Delhi",
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&h=600&fit=crop",
    badge: "New",
    type: "House",
    propertyType: "house",
    purpose: "rent", 
    featured: true,
    latitude: 28.5921,
    longitude: 77.0460,
    // New Details
    configuration: "5 BHK Independent Duplex",
    facing: "North-East Facing",
    isLand: false,
    parking: "Open Space for 3 Vehicles",
    furnishing: "Unfurnished",
    policies: "11-Month Lease, 2 Months Security Deposit",
  },
  {
    id: 4,
    title: "Contemporary Villa in Goa",
    price: "₹1,80,00,000",
    rawPrice: 18000000,
    beds: 3,
    baths: 3,
    sqft: "3,200",
    location: "Calangute, Goa",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&h=600&fit=crop",
    badge: "Featured",
    type: "Villa",
    propertyType: "villa",
    purpose: "buy",
    featured: true,
    latitude: 15.5494,
    longitude: 73.7626,
    // New Details
    configuration: "3 BHK Luxury Holiday Home",
    facing: "North Facing",
    isLand: false,
    parking: "Dedicated Private Garage",
    furnishing: "Fully Furnished",
    policies: "Gated Community",
  },
  {
    id: 5,
    title: "Smart Home in Hyderabad",
    price: "₹85,00,000",
    rawPrice: 8500000,
    beds: 3,
    baths: 2,
    sqft: "2,100",
    location: "HITEC City, Hyderabad",
    image: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&h=600&fit=crop",
    badge: "Smart",
    type: "Apartment",
    propertyType: "apartment",
    purpose: "buy",
    featured: true,
    latitude: 17.4435,
    longitude: 78.3772,
    // New Details
    configuration: "3 BHK Smart Apartment",
    facing: "South Facing",
    isLand: false,
    parking: "1 Basement Parking Slot",
    furnishing: "Semi-Furnished",
    policies: "Corporate Leasing Welcomed",
  },
  {
    id: 6,
    title: "Agriculture Land in Salem",
    price: "₹48,00,000",
    rawPrice: 4800000,
    landArea: "3 Acres",
    facing: "East Facing Main Road",
    approval: "Patta Land",
    location: "Salem",
    image: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&h=600&fit=crop",
    badge: "Land",
    type: "Agriculture",
    propertyType: "land",
    purpose: "buy",
    featured: true,
    isLand: true,
    latitude: 11.6643,
    longitude: 78.1460,
    // New Details for Land
    configuration: "Farm Land",
    soilType: "Red Loam",
    waterSource: "Free Agriculture Well and Borewell",
    electricity: "3-Phase Power Connection",
    approvalStatus: "Single-Owner Patta",
  },
];